#Docker Syntax Version
version: "3.9"
# Services
# context = use current directly,
# volume - updates on local to update on docker,
# command - command to run service
# args- if running build argument where dev = true
# command #2 Runs in Steps when ever Call "passes"?
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    # run database first and app will run after so when app is ready database is already started
    depends_on:
      - db
  # step 1 create a database inside postgress
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      # set intial database config for local (hard coded )
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data:
# PS docker volume rm pcrecipebuilder_dev-db-data to clear database and start a new one?
