name: Checks
# run jobs on push
on: [push]
# tset-lint job
# run on linix machine
# Step 1: Log into Docker with creditianals
# step 2: checkout? access the code(Make code avaiable)
# step 3 test with maange.py
# step 4 test with flake 8
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{  secrets.KLIFF_DOCKERHUB }}
          password: ${{  secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
